name: Build & Push Backend

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: akaidmaru
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push
        run: |
          docker build -t ghcr.io/akaidmaru/proyectoIntegradorBackend-team1:latest .
          docker push ghcr.io/akaidmaru/proyectoIntegradorBackend-team1:latest